[package]
name = "rust-sandbox"
description = "Rust sandbox"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.41.0", features = ["rt-multi-thread", "macros", "time", "net", "io-util"] }
futures = "0.3.31"
bytes = "1"